# Generated by Django 3.2.9 on 2021-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcodes',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
