# Generated by Django 3.2.9 on 2022-01-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_newcodes_codeurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='expimg/')),
            ],
        ),
    ]
