# Generated by Django 3.2.9 on 2022-04-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_name', models.CharField(max_length=200)),
                ('files', models.FileField(upload_to='file_pdf/')),
                ('files_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
